### PR TITLE
Add missing `quantity` to Subscription.list/1

### PR DESCRIPTION
**Pull request by MMore**
Hello,

thanks a lot for your library. I guess you're not using `quantity` based subscriptions. I do, so I've added it :)

### CODE REVIEW

**Comment by imricardoramos** [comment]
Hey @MMore thanks for your PR!
Seems the `quantity` attribute is also missing from the [update function](https://developer.paddle.com/api-reference/b3A6MzA3NDQ3MzQ-update-user#request-body). Could you add it to the typespec there?

**Comment by MMore** [comment]
Sure. I hope that's ok for you.

BTW: No need to rush for a release, I saw another thing with the `prices` parameter in PayLink.generate/1 which needs to be adjusted. Will do that soon.

**Comment by imricardoramos** [comment]
Hey @MMore I've removed `quantity` from update return body, since [the docs](https://developer.paddle.com/api-reference/b3A6MzA3NDQ3MzQ-update-user#Responses) don't show it being returned.

**Comment by imricardoramos** [comment]
> BTW: No need to rush for a release, I saw another thing with the prices parameter in PayLink.generate/1 which needs to be adjusted. Will do that soon.

Sure! feel free to open another PR whenever you want. Thanks again!

**Pull request merged**
